namespace $ {

	/**
	 * Tests of the export.
	 *
	 * The real acceptance is elsewhere and cannot be a unit test: the output has to
	 * be dropped into `bog/` and built by mam. `bog/vmap/demo/` is that check,
	 * generated by this code and kept as a standing one. What is here are the
	 * decisions that would otherwise fail silently — placement, declaration order
	 * and decorators — plus the refusals.
	 *
	 * `d` keeps `$` out of the string literals: mam builds its dependency graph by
	 * a regexp over sources, literals included, so a fixture class name spelled
	 * literally would be resolved as a module path.
	 */
	const d = '$'

	const page = [
		`${d}bog_site_page ${d}mol_view`,
		`	Hero ${d}bog_site_hero`,
		`	greeting = Hero title`,
		`	sub / <= Hero`,
		``,
	].join( '\n' )

	const hero = `${d}bog_site_hero ${d}mol_view\n\ttitle \\Hi\n\tcount? 0\n\tplain \\x\n`

	/**
	 * Two artboards and one free part beside them: `Home` and `About` carry a `sub`
	 * of their own and so are pages, `Loose` carries none and so is not.
	 */
	const pages = [
		`${d}bog_site_page ${d}mol_view`,
		`	Head ${d}mol_view`,
		`	Loose ${d}mol_view`,
		`	Home ${d}mol_view sub / <= Head`,
		`	About ${d}mol_view sub /`,
		`	sub /`,
		`		<= Home`,
		`		<= About`,
		`		<= Loose`,
		``,
	].join( '\n' )

	/** Text of one file of the module, or empty when the module carries none. */
	function file_of( module: $bog_vmap_app_export_module, suffix: string ) {
		return module.files.find( file => file.name.endsWith( suffix ) )?.text ?? ''
	}

	$mol_test({

		/**
		 * Placement is not free. Mam turns a class name into a path by replacing every
		 * underscore with a slash, so a module put anywhere else fails to build while
		 * looking entirely correct — the one failure this whole task exists to rule out.
		 */
		'module path comes from the class names'( $ ) {

			$mol_assert_equal(
				$.$bog_vmap_app_export_path([ `${d}bog_site_page`, `${d}bog_site_hero` ]),
				'bog/site',
			)

			$mol_assert_equal(
				$.$bog_vmap_app_export_path([ `${d}bog_site_page` ]),
				'bog/site/page',
			)

			$mol_assert_equal(
				$.$bog_vmap_app_export_path([ `${d}bog_site_page`, `${d}bog_site_page_hero` ]),
				'bog/site/page',
			)

		},

		'classes of different packs cannot be one module'( $ ) {

			$mol_assert_fail(
				()=> $.$bog_vmap_app_export_path([ `${d}bog_site_page`, `${d}hyoo_other_page` ]),
				Error,
			)

			$mol_assert_fail(
				()=> $.$bog_vmap_app_export_path([ `${d}bog_one`, `${d}bog_two` ]),
				Error,
			)

			$mol_assert_fail( ()=> $.$bog_vmap_app_export_path([]), Error )

		},

		/**
		 * `class $A extends $[ '$B' ]` takes its base at definition time and the
		 * generator emits declarations in the order it got them, so an heir above its
		 * base inherits `undefined`. The document is written heir first here on
		 * purpose.
		 */
		'a base is declared before its heir'( $ ) {

			const own = `${d}bog_site_hero_big ${d}bog_site_hero\n\ttitle \\Big\n`
			const module = $.$bog_vmap_app_export_build([
				{ source: own },
				{ source: page },
				{ source: hero },
			], `${d}bog_site_page` )

			const tree = file_of( module, '.view.tree' )

			$mol_assert_equal( tree.indexOf( `${d}bog_site_hero ` ) < tree.indexOf( `${d}bog_site_hero_big ` ), true )

		},

		'the emitted declaration parses back into the same classes'( $ ) {

			const module = $.$bog_vmap_app_export_build([ { source: page }, { source: hero } ])

			const back = $.$mol_view_tree2_normalize(
				$.$mol_tree2_from_string( file_of( module, '.view.tree' ), 'export' )
			)

			/**
			 * Input order, because neither is the base of the other. A sub-view
			 * reference does NOT constrain the order: the generator writes a
			 * `new this.$[ name ]()` resolved at call time, and only the `extends`
			 * clause is evaluated when the class is defined.
			 */
			$mol_assert_like(
				back.kids.map( cl => cl.type ),
				[ `${d}bog_site_page`, `${d}bog_site_hero` ],
			)

		},

		/**
		 * A property memoized in the preview has to be memoized in the export, or the
		 * two drift and nothing says so: an override without a decorator simply has no
		 * atom, so it returns a fresh value while the DOM keeps the old one.
		 */
		'a hand written body carries its decorators'( $ ) {

			const module = $.$bog_vmap_app_export_build([
				{ source: page },
				{ source: hero, js: 'count( next?: number ) {\n\treturn next ?? 7\n}\n' },
			])

			const ts = file_of( module, '.view.ts' )

			$mol_assert_equal( ts.includes( `export class ${d}bog_site_hero extends $.${d}bog_site_hero {` ), true )

			// Over the method, the way a person writes it, and nowhere else: the
			// expression form belongs to the scene, which cannot write a decorator
			// into the string it hands to `new Function`.
			$mol_assert_equal( ts.includes( `\t\t@ ${d}mol_mem\n\t\tcount( next?: number ) {` ), true )
			$mol_assert_equal( ts.includes( '.prototype' ), false )

			/** `title` and `plain` carry no sign, so the generated base does not memoize them either. */
			$mol_assert_equal( ts.includes( '"title"' ), false )
			$mol_assert_equal( ts.includes( '"plain"' ), false )

		},

		/**
		 * The file that goes out is still a file the editor can read back: the body
		 * with decorators in it slices into exactly the properties it was cut from.
		 * The export and the code panel cut with the same function, so this is a
		 * check that the decorator did not land somewhere that breaks the cut.
		 */
		'the decorated body slices back into the same properties'( $ ) {

			const module = $.$bog_vmap_app_export_build([
				{ source: page },
				{ source: hero, js: 'count( next?: number ) {\n\treturn next ?? 7\n}\n' },
			])

			const ts = file_of( module, '.view.ts' )
			const body = ts.slice(
				ts.indexOf( '{', ts.indexOf( 'export class' ) ) + 1,
				ts.lastIndexOf( '\t}' ),
			)

			$mol_assert_like( [ ... $.$bog_vmap_app_code_props_js( body ).keys() ], [ 'count' ] )

		},

		/** The decorator goes under the comment of the method, not above it. */
		'a documented method keeps its comment over the decorator'( $ ) {

			const module = $.$bog_vmap_app_export_build([
				{ source: page },
				{
					source: hero,
					js: '/** How many. */\ncount( next?: number ) {\n\treturn next ?? 7\n}\n',
				},
			])

			$mol_assert_equal(
				file_of( module, '.view.ts' ).includes(
					`\t\t/** How many. */\n\t\t@ ${d}mol_mem\n\t\tcount( next?: number ) {`
				),
				true,
			)

		},

		/**
		 * A body the slicer cannot cut keeps the old form: braces are counted, not
		 * parsed, so a `}` inside a string defeats it. An ugly file is the right
		 * trade — a body that loses its decorators loses its atoms silently.
		 */
		'a body that cannot be sliced keeps the decorators after the class'( $ ) {

			const module = $.$bog_vmap_app_export_build([
				{ source: page },
				{ source: hero, js: 'count( next?: number ) {\n\treturn next ?? "}"\n}\n' },
			])

			const ts = file_of( module, '.view.ts' )

			$mol_assert_equal( ts.includes( `;( ${d}mol_mem( ${d}bog_site_hero.prototype, "count" ) )` ), true )

		},

		'a class without a body gets no file of its own at all'( $ ) {

			const module = $.$bog_vmap_app_export_build([ { source: page }, { source: hero } ])

			// Not an empty namespace: a module written by a person carries no file
			// with nothing in it.
			$mol_assert_equal( module.files.some( file => file.name.endsWith( '.view.ts' ) ), false )
			$mol_assert_equal( module.files.some( file => file.name.endsWith( '.view.css' ) ), false )

		},

		/**
		 * The stylesheet goes out as a stylesheet. mam compiles every `.css` of a
		 * module into the bundle, the way `mol/view/view/view.css` travels, so there
		 * is nothing to attach and nothing to escape: user text that would have torn
		 * a template literal apart is just text in a file.
		 */
		'a stylesheet is a stylesheet, verbatim'( $ ) {

			const css = '[bog_site_hero]{ content: "` ' + '${x}' + '" }'

			const module = $.$bog_vmap_app_export_build([
				{ source: page },
				{ source: hero, css },
			])

			$mol_assert_equal( file_of( module, '.view.css' ), css + '\n' )
			$mol_assert_equal( module.files.some( file => file.name.endsWith( '.view.css.ts' ) ), false )

		},

		'index.html instantiates the root class'( $ ) {

			const module = $.$bog_vmap_app_export_build([ { source: page }, { source: hero } ], `${d}bog_site_page` )

			$mol_assert_equal( module.root, `${d}bog_site_page` )
			$mol_assert_equal(
				file_of( module, 'index.html' ).includes( `mol_view_root="${d}bog_site_page"` ),
				true,
			)

		},

		/**
		 * The module carries what a person would have written and nothing else: the
		 * declaration, what mam needs to build it, and a page. A body and a
		 * stylesheet appear only when the document has them.
		 */
		'the module is the files a person would have written'( $ ) {

			const module = $.$bog_vmap_app_export_build([ { source: page }, { source: hero } ])

			$mol_assert_equal( module.path, 'bog/site' )
			$mol_assert_equal( module.name, 'site' )

			$mol_assert_like(
				module.files.map( file => file.name ),
				[
					'site.view.tree',
					'site.meta.tree',
					'index.html',
				],
			)

			const full = $.$bog_vmap_app_export_build([
				{ source: page },
				{ source: hero, js: 'count( next?: number ) {\n\treturn next ?? 7\n}\n', css: '[bog_site_hero]{}' },
			])

			$mol_assert_like(
				full.files.map( file => file.name ),
				[
					'site.view.tree',
					'site.view.ts',
					'site.view.css',
					'site.meta.tree',
					'index.html',
				],
			)

		},

		'a root outside the document is refused'( $ ) {

			$mol_assert_fail(
				()=> $.$bog_vmap_app_export_build([ { source: page }, { source: hero } ], `${d}bog_site_nope` ),
				Error,
			)

		},

		'a class declared twice is refused'( $ ) {

			$mol_assert_fail(
				()=> $.$bog_vmap_app_export_build([ { source: hero }, { source: hero } ]),
				Error,
			)

		},

		/**
		 * The acceptance of the artboards: what an export carries of a page is the
		 * tree it shows and the flex properties it was set with, and not one number
		 * of the canvas.
		 *
		 * The placement of free parts cannot leak here by construction — it never
		 * enters the document, it rides `spots` to the scene and is turned into
		 * rules there — and this is the test that keeps that true from the far end,
		 * where the leak would be shipped rather than merely visible.
		 */
		'an artboard exports as the tree it shows, with no coordinate in it'( $ ) {

			const board = [
				`${d}bog_site_page ${d}mol_view`,
				`	Head ${d}mol_view`,
				`	Foot ${d}mol_view`,
				`	Loose ${d}mol_view`,
				`	Board ${d}mol_view`,
				`		style *`,
				`			width \\1280px`,
				`			flexDirection \\column`,
				`		sub /`,
				`			<= Head`,
				`			<= Foot`,
				`	sub /`,
				`		<= Board`,
				`		<= Loose`,
				``,
			].join( '\n' )

			const tree = file_of( $.$bog_vmap_app_export_build([ { source: board } ]), '.view.tree' )

			$mol_assert_equal( tree, board )

			// Nothing of the desk: no coordinates, and no absolute positioning to
			// apply them with.
			const css = file_of( $.$bog_vmap_app_export_build([ { source: board } ]), '.view.css' )
			$mol_assert_equal( /\bleft\b|\btop\b|position/.test( css ), false )

		},

		/**
		 * Two artboards are two pages, and pages need an address. The router is a
		 * class of its own rather than an edit of the document, because the document
		 * goes out byte for byte the way the editor holds it.
		 */
		'a document of two artboards exports with a router over them'( $ ) {

			const module = $.$bog_vmap_app_export_build([ { source: pages }, { source: hero } ])

			const tree = file_of( module, '.view.tree' )
			const ts = file_of( module, '.view.ts' )

			// The document itself is untouched, and the router is one class after it.
			$mol_assert_equal( tree, pages + hero + `${d}bog_site_app ${d}mol_view\n\tDoc ${d}bog_site_page\n` )

			// The base of the router is declared above it, as every base has to be.
			$mol_assert_equal( tree.indexOf( `${d}bog_site_page ` ) < tree.indexOf( `${d}bog_site_app ` ), true )

			// Both pages are addressable, and the first one is what a bare address opens.
			$mol_assert_equal( ts.includes( `switch( this.$.${d}mol_state_arg.value( 'page' ) ) {` ), true )
			$mol_assert_equal( ts.includes( `case "About": return [ doc.About() ]` ), true )
			$mol_assert_equal( ts.includes( `default: return [ doc.Home() ]` ), true )

			// A free part is not a page: it has no `sub` of its own, and the router
			// never names it.
			$mol_assert_equal( ts.includes( 'Loose' ), false )

			// The page is reached through the document, which is declared and never
			// drawn, so nothing but the chosen page builds any DOM.
			$mol_assert_equal( ts.includes( 'const doc = this.Doc()' ), true )

			$mol_assert_equal( module.root, `${d}bog_site_app` )
			$mol_assert_equal( file_of( module, 'index.html' ).includes( `mol_view_root="${d}bog_site_app"` ), true )

		},

		/**
		 * The router carries no coordinate either. Two artboards lie side by side on
		 * the canvas by numbers that ride `spots`, and a page that came out placed
		 * absolutely would be that desk shipped to a reader.
		 */
		'a routed document ships no placement'( $ ) {

			const module = $.$bog_vmap_app_export_build([ { source: pages }, { source: hero } ])

			$mol_assert_equal( /\bleft\b|\btop\b|position/.test( file_of( module, '.view.css' ) ), false )
			$mol_assert_equal( /\bx\b|\by\b|spot/.test( file_of( module, '.view.ts' ) ), false )

		},

		/**
		 * A router over one page would be a class that always answers the same thing.
		 * One page stays one page: no router class, no file to put it in, and the
		 * document itself at the root.
		 */
		'a document of one artboard gets no router'( $ ) {

			const one = [
				`${d}bog_site_page ${d}mol_view`,
				`	Head ${d}mol_view`,
				`	Home ${d}mol_view sub / <= Head`,
				`	sub / <= Home`,
				``,
			].join( '\n' )

			const module = $.$bog_vmap_app_export_build([ { source: one } ])

			$mol_assert_equal( file_of( module, '.view.tree' ), one )
			$mol_assert_equal( module.root, `${d}bog_site_page` )
			// One class, so the path is `bog/site/page` and the module is named after
			// its last segment.
			$mol_assert_like(
				module.files.map( file => file.name ),
				[ 'page.view.tree', 'page.meta.tree', 'index.html' ],
			)

		},

		/**
		 * Placement is not free for the router either: a name adding a segment to the
		 * longest common prefix would move the whole module into a folder that does
		 * not exist.
		 */
		'the router leaves the module where the document put it'( $ ) {

			const module = $.$bog_vmap_app_export_build([ { source: pages }, { source: hero } ])

			$mol_assert_equal( module.path, 'bog/site' )
			$mol_assert_equal( module.root, `${d}bog_site_app` )
			$mol_assert_equal(
				$.$bog_vmap_app_export_path([ `${d}bog_site_page`, `${d}bog_site_hero`, module.root ]),
				'bog/site',
			)

			// A document of a single class sits one segment deeper, and the router
			// follows it there instead of pulling it back up.
			const deep = $.$bog_vmap_app_export_build([ { source: pages } ])

			$mol_assert_equal( deep.path, 'bog/site/page' )
			$mol_assert_equal( deep.root, `${d}bog_site_page_app` )
			$mol_assert_equal(
				$.$bog_vmap_app_export_path([ `${d}bog_site_page`, deep.root ]),
				'bog/site/page',
			)

		},

		'a router named by the document takes the next free name'( $ ) {

			const module = $.$bog_vmap_app_export_build([
				{ source: pages },
				{ source: `${d}bog_site_app ${d}mol_view\n\ttitle \\Taken\n` },
			], `${d}bog_site_page` )

			$mol_assert_equal( module.root, `${d}bog_site_app2` )
			$mol_assert_equal( file_of( module, '.view.tree' ).includes( `${d}bog_site_app2 ${d}mol_view` ), true )

		},

		/**
		 * The divergence of section 10, caught where the author can still do
		 * something about it. A body without types runs in the preview through
		 * `new Function` and fails the export, which compiles it with `strict`.
		 */
		'a body that would not pass strict is named before the export'( $ ) {

			const notes = $.$bog_vmap_app_export_untyped( 'count( next ) {\n\treturn next ?? 7\n}\n' )

			$mol_assert_equal( notes.length, 1 )
			$mol_assert_equal( notes[0].method, 'count' )
			$mol_assert_equal( notes[0].param, 'next' )
			$mol_assert_equal( notes[0].line, 1 )

			const error = $mol_assert_fail(
				()=> $.$bog_vmap_app_export_build([
					{ source: page },
					{ source: hero, js: 'title() {\n\treturn "hi"\n}\n\ncount( next ) {\n\treturn next ?? 7\n}\n' },
				]),
				Error,
			)

			// The refusal names the class, the line, the method and the parameter —
			// everything needed to go and fix it.
			$mol_assert_equal( error.message.includes( `${d}bog_site_hero` ), true )
			$mol_assert_equal( error.message.includes( 'строка 5' ), true )
			$mol_assert_equal( error.message.includes( 'count' ), true )
			$mol_assert_equal( error.message.includes( 'next' ), true )

		},

		/**
		 * What the check must NOT say, or the editor would cry over working code and
		 * be turned off. A default value is a type, an arrow is typed by context, and
		 * a statement is not a method.
		 */
		'a typed body passes untouched'( $ ) {

			const js = [
				`@ ${d}mol_mem`,
				'count( next?: number ) {',
				'	return next ?? 7',
				'}',
				'',
				'sum( rest = 0 ) {',
				'	return this.items().map( item => item.value() ).reduce( ( a: number, b: number )=> a + b, rest )',
				'}',
				'',
				'title() {',
				'	if( this.count() ) return "many"',
				'	for( const item of this.items() ) return "one"',
				'	return ""',
				'}',
				'',
			].join( '\n' )

			$mol_assert_like( $.$bog_vmap_app_export_untyped( js ), [] )

			const module = $.$bog_vmap_app_export_build([ { source: page }, { source: hero, js } ])

			$mol_assert_equal( file_of( module, '.view.ts' ).includes( 'count( next?: number )' ), true )

		},

		/**
		 * The forms a naive search for «a parameter without a type» gets wrong, one
		 * assertion each.
		 *
		 * The two mistakes do not cost the same. A complaint refuses the export, so a
		 * false one locks the author inside the editor with no way out, while a missed
		 * one costs a build failure that explains itself. Every line below is
		 * therefore an assertion of SILENCE, and the ones that are genuine errors
		 * passed over — the destructuring, the object literal method — are silence on
		 * purpose and named as misses in the docs.
		 */
		'the check keeps quiet on everything it is not sure of'( $ ) {

			const quiet = ( js: string )=> $mol_assert_like( $.$bog_vmap_app_export_untyped( js ), [] )

			// A destructured parameter is an error of the same kind, and naming it
			// sensibly is beyond a search over text. Missed on purpose.
			quiet( 'render( { head, foot } ) {\n\treturn [ head, foot ]\n}\n' )

			// An arrow written as a class property. Its parameter is untyped, and the
			// line is not a method head at all, so it is left alone.
			quiet( 'handler = ( event )=> event.type\n' )

			// A `this` parameter is not a parameter of the caller.
			quiet( 'pick( this: $, id: string ) {\n\treturn id\n}\n' )

			// A generic method, typed through its own type parameter.
			quiet( 'first< Item >( list: Item[] ) {\n\treturn list[0]\n}\n' )

			// An overload signature carries no body, so it is not a head. Missed even
			// with an untyped parameter, and that is the safe direction.
			quiet( 'plus( a ): number\nplus( a: number ) {\n\treturn a\n}\n' )

			// Optional and rest parameters, both typed.
			quiet( 'join( a?: string, ... rest: string[] ) {\n\treturn [ a, ... rest ]\n}\n' )

			// A signature quoted inside a template literal is not a signature. This is
			// the one that would fire on text the author never meant as code.
			quiet( 'sample() {\n\treturn `\ncount( next ) {\n`\n}\n' )

			// The same inside comments, both kinds.
			quiet( 'sample() {\n\treturn 1\n}\n// count( next ) {\n' )
			quiet( 'sample() {\n\treturn 1\n}\n/*\ncount( next ) {\n*/\n' )

			// A method of an object literal inside a body: indented, therefore a
			// statement rather than a head. Missed on purpose.
			quiet( 'config() {\n\treturn {\n\t\topen( next ) { return next },\n\t}\n}\n' )

			// A call at the start of a line inside a method reads exactly like a head
			// to a search that ignores indentation.
			quiet( 'run() {\n\tsuper( next )\n\tthis.compute( x )\n}\n' )

		},

		/**
		 * The other half of the same rule: what the check IS sure of, it says. A body
		 * that reaches the export in any of these shapes does not build.
		 */
		'the check does say the parameter it is sure about'( $ ) {

			const first = ( js: string )=> $.$bog_vmap_app_export_untyped( js )[0]

			// A `this` parameter beside an untyped one: only the second is named.
			const beside = $.$bog_vmap_app_export_untyped( 'pick( this: $, id ) {\n\treturn id\n}\n' )
			$mol_assert_equal( beside.length, 1 )
			$mol_assert_equal( beside[0].param, 'id' )

			// A generic whose value parameter carries no type of its own.
			$mol_assert_equal( first( 'first< Item >( list ) {\n\treturn list[0]\n}\n' ).param, 'list' )

			// A rest parameter, named without its dots and suggested with them.
			const rest = first( 'join( ... parts ) {\n\treturn parts\n}\n' )
			$mol_assert_equal( rest.param, 'parts' )
			$mol_assert_equal( rest.text.includes( '... parts: number[]' ), true )

			// An optional parameter without a type is untyped all the same.
			$mol_assert_equal( first( 'load( id? ) {\n\treturn id\n}\n' ).param, 'id' )

			// A setter and an async method are heads like any other.
			$mol_assert_equal( first( 'set title( next ) {\n\treturn next\n}\n' ).method, 'title' )
			$mol_assert_equal( first( 'async load( id ) {\n\treturn id\n}\n' ).method, 'load' )

			// A head split over several lines is still one head, reported at the line
			// the author reads as its first.
			const split = first( 'sum(\n\ta: number,\n\tb,\n) {\n\treturn a + b\n}\n' )
			$mol_assert_equal( split.param, 'b' )
			$mol_assert_equal( split.line, 1 )

			// A body written with an indent of its own is checked at that indent, or
			// the check would silently do nothing for a whole class of editors.
			const inset = first( '\tcount( next ) {\n\t\treturn next\n\t}\n' )
			$mol_assert_equal( inset.param, 'next' )

			// The message is an instruction: what to write, spelled out.
			$mol_assert_equal(
				first( 'count( next ) {\n\treturn next\n}\n' ).text.includes( 'count( next?: number )' ),
				true,
			)

		},

		'a cycle of bases is refused rather than hung'( $ ) {

			$mol_assert_fail(
				()=> $.$bog_vmap_app_export_build([
					{ source: `${d}bog_site_a ${d}bog_site_b\n\tx \\1\n` },
					{ source: `${d}bog_site_b ${d}bog_site_a\n\ty \\2\n` },
				]),
				Error,
			)

		},

	})

}
