namespace $ {

	/**
	 * Tests of the export.
	 *
	 * The real acceptance is elsewhere and cannot be a unit test: the output has to
	 * be dropped into `bog/` and built by mam. `bog/vmap/demo/` is that check,
	 * generated by this code and kept as a standing one. What is here are the
	 * decisions that would otherwise fail silently — placement, declaration order
	 * and decorators — plus the refusals.
	 *
	 * `d` keeps `$` out of the string literals: mam builds its dependency graph by
	 * a regexp over sources, literals included, so a fixture class name spelled
	 * literally would be resolved as a module path.
	 */
	const d = '$'

	const page = [
		`${d}bog_site_page ${d}mol_view`,
		`	Hero ${d}bog_site_hero`,
		`	greeting = Hero title`,
		`	sub / <= Hero`,
		``,
	].join( '\n' )

	const hero = `${d}bog_site_hero ${d}mol_view\n\ttitle \\Hi\n\tcount? 0\n\tplain \\x\n`

	function file_of( module: $bog_vmap_app_export_module, suffix: string ) {
		return module.files.find( file => file.name.endsWith( suffix ) )!.text
	}

	$mol_test({

		/**
		 * Placement is not free. Mam turns a class name into a path by replacing every
		 * underscore with a slash, so a module put anywhere else fails to build while
		 * looking entirely correct — the one failure this whole task exists to rule out.
		 */
		'module path comes from the class names'( $ ) {

			$mol_assert_equal(
				$.$bog_vmap_app_export_path([ `${d}bog_site_page`, `${d}bog_site_hero` ]),
				'bog/site',
			)

			$mol_assert_equal(
				$.$bog_vmap_app_export_path([ `${d}bog_site_page` ]),
				'bog/site/page',
			)

			$mol_assert_equal(
				$.$bog_vmap_app_export_path([ `${d}bog_site_page`, `${d}bog_site_page_hero` ]),
				'bog/site/page',
			)

		},

		'classes of different packs cannot be one module'( $ ) {

			$mol_assert_fail(
				()=> $.$bog_vmap_app_export_path([ `${d}bog_site_page`, `${d}hyoo_other_page` ]),
				Error,
			)

			$mol_assert_fail(
				()=> $.$bog_vmap_app_export_path([ `${d}bog_one`, `${d}bog_two` ]),
				Error,
			)

			$mol_assert_fail( ()=> $.$bog_vmap_app_export_path([]), Error )

		},

		/**
		 * `class $A extends $[ '$B' ]` takes its base at definition time and the
		 * generator emits declarations in the order it got them, so an heir above its
		 * base inherits `undefined`. The document is written heir first here on
		 * purpose.
		 */
		'a base is declared before its heir'( $ ) {

			const own = `${d}bog_site_hero_big ${d}bog_site_hero\n\ttitle \\Big\n`
			const module = $.$bog_vmap_app_export_build([
				{ source: own },
				{ source: page },
				{ source: hero },
			], `${d}bog_site_page` )

			const tree = file_of( module, '.view.tree' )

			$mol_assert_equal( tree.indexOf( `${d}bog_site_hero ` ) < tree.indexOf( `${d}bog_site_hero_big ` ), true )

		},

		'the emitted declaration parses back into the same classes'( $ ) {

			const module = $.$bog_vmap_app_export_build([ { source: page }, { source: hero } ])

			const back = $.$mol_view_tree2_normalize(
				$.$mol_tree2_from_string( file_of( module, '.view.tree' ), 'export' )
			)

			/**
			 * Input order, because neither is the base of the other. A sub-view
			 * reference does NOT constrain the order: the generator writes a
			 * `new this.$[ name ]()` resolved at call time, and only the `extends`
			 * clause is evaluated when the class is defined.
			 */
			$mol_assert_like(
				back.kids.map( cl => cl.type ),
				[ `${d}bog_site_page`, `${d}bog_site_hero` ],
			)

		},

		/**
		 * A property memoized in the preview has to be memoized in the export, or the
		 * two drift and nothing says so: an override without a decorator simply has no
		 * atom, so it returns a fresh value while the DOM keeps the old one.
		 */
		'a hand written body carries its decorators'( $ ) {

			const module = $.$bog_vmap_app_export_build([
				{ source: page },
				{ source: hero, js: 'count( next ) {\n\treturn next ?? 7\n}\n' },
			])

			const ts = file_of( module, '.view.ts' )

			$mol_assert_equal( ts.includes( `export class ${d}bog_site_hero extends $.${d}bog_site_hero {` ), true )
			$mol_assert_equal( ts.includes( `;( ${d}mol_mem( ${d}bog_site_hero.prototype, "count" ) )` ), true )

			/** `title` and `plain` carry no sign, so the generated base does not memoize them either. */
			$mol_assert_equal( ts.includes( '"title"' ), false )
			$mol_assert_equal( ts.includes( '"plain"' ), false )

		},

		'a class without a body gets no subclass at all'( $ ) {

			const module = $.$bog_vmap_app_export_build([ { source: page }, { source: hero } ])

			$mol_assert_equal( file_of( module, '.view.ts' ), 'namespace $.$$ {\n\n}\n' )

		},

		/**
		 * The stylesheet is user text. A backtick or a `${` in it would tear a
		 * template literal apart, which is why both ends go through `JSON.stringify`.
		 */
		'a stylesheet is embedded as data, not as a template literal'( $ ) {

			const css = '[bog_site_hero]{ content: "` ' + '${x}' + '" }'

			const module = $.$bog_vmap_app_export_build([
				{ source: page },
				{ source: hero, css },
			])

			const out = file_of( module, '.view.css.ts' )

			/**
			 * The whole emitted call, spelled out. A backtick does survive into the
			 * file — it just sits inside a double quoted string, where it is one more
			 * character. Asserting its absence would be asserting the wrong thing; what
			 * matters is that neither it nor the `${` can terminate the literal.
			 */
			$mol_assert_equal(
				out.includes(
					`\t${d}mol_style_attach( ${ JSON.stringify( `${d}bog_site_hero` ) }, ${ JSON.stringify( css ) } )`
				),
				true,
			)

		},

		'index.html instantiates the root class'( $ ) {

			const module = $.$bog_vmap_app_export_build([ { source: page }, { source: hero } ], `${d}bog_site_page` )

			$mol_assert_equal( module.root, `${d}bog_site_page` )
			$mol_assert_equal(
				file_of( module, 'index.html' ).includes( `mol_view_root="${d}bog_site_page"` ),
				true,
			)

		},

		'the module is exactly five files'( $ ) {

			const module = $.$bog_vmap_app_export_build([ { source: page }, { source: hero } ])

			$mol_assert_equal( module.path, 'bog/site' )
			$mol_assert_equal( module.name, 'site' )

			$mol_assert_like(
				module.files.map( file => file.name ),
				[
					'site.view.tree',
					'site.view.ts',
					'site.view.css.ts',
					'site.meta.tree',
					'index.html',
				],
			)

		},

		'a root outside the document is refused'( $ ) {

			$mol_assert_fail(
				()=> $.$bog_vmap_app_export_build([ { source: page }, { source: hero } ], `${d}bog_site_nope` ),
				Error,
			)

		},

		'a class declared twice is refused'( $ ) {

			$mol_assert_fail(
				()=> $.$bog_vmap_app_export_build([ { source: hero }, { source: hero } ]),
				Error,
			)

		},

		'a cycle of bases is refused rather than hung'( $ ) {

			$mol_assert_fail(
				()=> $.$bog_vmap_app_export_build([
					{ source: `${d}bog_site_a ${d}bog_site_b\n\tx \\1\n` },
					{ source: `${d}bog_site_b ${d}bog_site_a\n\ty \\2\n` },
				]),
				Error,
			)

		},

	})

}
